### ISSUE TITLE
An error occurred trying to start process 'py' with working directory

### ISSUE THREAD

**Issue by srihari9n** [yakovypg/Ypdf#1]
./ypdf compress -i /Users/srihari/Desktop/rules.pdf -o /Users/srihari/Desktop/new_rules.pdf -Q 0.75

I tried running this command after building the ypdf using the instructions given in readme. I got an error : 

An error occurred trying to start process 'py' with working directory '/Users/srihari/Desktop'. No such file or directory

**Comment by yakovypg** [comment]
Do you have python 3 installed on your computer? What alias does python have?

To perform this action, python 3 should be installed. Make sure that it is installed on your computer. By default (for OS Windows) the program searches for python using "py". If the PATH/alias for python does not match "py", specify it manually. You can read more about this in the "Global config" section in README.

To specify a path for python, use the following command
```
./ypdf config --python-alias=PATH_TO_PYTHON --save-config=true
```

**Comment by srihari9n** [comment]
Set the alias py to python3. Still no use. Tried setting the alias to the full path of python. to `python3` to `py`(after setting alias). Giving same error.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/101564310/205297980-14e652fa-aec1-4b5d-b3ce-19fcf1a41675.png">

**Comment by yakovypg** [comment]
Try to build a new version of the application. Has the issue disappeared?

**Comment by srihari9n** [comment]
@yakovypg  changed the dll location to root directory of my user from Desktop and it works.

But now I have a different question, I tried running this command : 

./ypdf compress -i /Users/srihari/Downloads/A17_FlightPlan.pdf -o /Users/srihari/Desktop/new_flight_plan.pdf

I expected the output pdf to be compressed to a smaller size. But the original pdf was of 20 mb and the output was 500 or so mb. 

What am i doing wrong?

**Comment by yakovypg** [comment]
To compress a document, first all images are extracted from it, then the extracted images are compressed, after which the original images are replaced with compressed ones. The Pillow module is used to compress images. Your document contains images that are already sufficiently compressed. Saving these images entails an increase in their weight (due to the method of saving). Because of this, the size of the PDF file increases.

The compression function is implemented without any special image compression methods or the structure of the PDF document as a whole. First of all, this function is designed to compress documents containing uncompressed images (for example, to compress a book containing high-quality images).

**Comment by srihari9n** [comment]
Okay @yakovypg  got it. You can close this issue but can you consider implementing a checking function of sorts which can indicate users if the document can be further compressed or not? That could be very useful to implement a case where user can keep the original document as is instead of trying to compress and increase file size.

**Comment by yakovypg** [comment]
Yes, of course. Added this feature.
